#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# pylint: disable=W1203

import sys
import atexit
import logging
import argparse

import Ice
Ice.loadSlice('icegauntlet.ice')
import IceGauntlet

class clienteAutenticacion(Ice.Application):
    def run(self, argv):
        print("HOLA")
        proxy = self.communicator().stringToProxy(argv[1])
        auth = IceGauntlet.AuthenticationPrx.checkedCast(proxy)

        if not auth:
            raise RuntimeError('Invalid proxy')

        auth.send(argv[4], argv[1], argv[2])

        return 0

sys.exit(clienteAutenticacion().main(sys.argv))