#!/usr/bin/env python3
#pylint: disable=W0632 
#Se desactiva debido a la manera de recoger los argumentos

'''
Script to run delete map
'''

import os
import sys
import subprocess

# Define command
_COMMAND_ = 'python3 rooms_tool_client.py -r "%(map_server_proxy)s" %(token)s %(roomName)s'

try:
    map_server_proxy, token, roomName = sys.argv[1:]
except ValueError:
    print('Command arguments: {} <map_server_proxy> <token> <roomName>'.format(
        os.path.basename(sys.argv[0]))
    )
    sys.exit(1)

# Compose command
final_command = _COMMAND_ % {
    'map_server_proxy': map_server_proxy,
    'token': token,
    'roomName':roomName
}

# Run command
subprocess.run(final_command,shell=True, stdout=sys.stdout)
sys.exit(0)
