#!/usr/bin/env python3

'''
Script to run game client
'''

import os
import sys
import subprocess

# Define command
_COMMAND_ = 'python3 dungeon_client.py "%(game_proxy)s"'

try:
    game_proxy = sys.argv[1]
except IndexError:
    print('Command arguments: {} <game_proxy>'.format(
        os.path.basename(sys.argv[0]))
    )
    sys.exit(1)

# Compose command
final_command = _COMMAND_ % {
    'game_proxy': game_proxy
}
#Run command
try:
    subprocess.run(final_command,shell=True, stdout=sys.stdout)
except KeyboardInterrupt:
    print("Programa detenido por teclado")
sys.exit(0)
