#!/usr/bin/env python3

'''
Script to run game client
'''

import os
import sys

try:
    import pexpect
except ImportError:
    print('Required library "pexpect" not exists. Install with pip and try again')
    sys.exit(1)

# Define command
_COMMAND_ = 'python3 dungeon_client.py "%(game_proxy)s"'

try:
    game_proxy = sys.argv[1]
except ValueError:
    print('Command arguments: {} <game_proxy>'.format(
        os.path.basename(sys.argv[0]))
    )
    sys.exit(1)

# Compose command
final_command = _COMMAND_ % {
    'game_proxy': game_proxy
}

# Run command
proc = pexpect.spawn(final_command, echo=False)
proc.logfile=sys.stdout.buffer
try:
    proc.expect([pexpect.EOF,pexpect.TIMEOUT],timeout=None)
except KeyboardInterrupt:
    print("Programa detenido por teclado")
sys.exit(0)
