#!/usr/bin/env python3

'''
Script to run map server
'''

import os
import sys

try:
    import pexpect
except ImportError:
    print('Required library "pexpect" not exists. Install with pip and try again')
    sys.exit(1)

# Define command to request new token
_COMMAND_ = 'python3 server.py --Ice.Config=Server.config "%(auth_proxy)s"'

# Get required arguments
try:
    proxy = sys.argv[1]
except IndexError:
    print('Command arguments: {} <proxy>'.format(
        os.path.basename(sys.argv[0]))
    )
    sys.exit(1)

# Compose command
final_command = _COMMAND_ % {
    'auth_proxy': proxy
}

# Run command
proc = pexpect.spawn(final_command, echo=False)
proc.logfile=sys.stdout.buffer
proc.expect([pexpect.EOF,pexpect.TIMEOUT],timeout=None)
sys.exit(0)