#!/usr/bin/env python3

'''
Script to run map server
'''

import os
import sys
import subprocess

# Define command
_COMMAND_ = 'python3 server.py --Ice.Config=Server.config "%(auth_proxy)s"'

# Get required arguments
try:
    proxy = sys.argv[1]
except IndexError:
    print('Command arguments: {} <proxy>'.format(
        os.path.basename(sys.argv[0]))
    )
    sys.exit(1)

# Compose command
final_command = _COMMAND_ % {
    'auth_proxy': proxy
}

# Run command
try:
    subprocess.run(final_command,shell=True, stdout=sys.stdout)
except KeyboardInterrupt:
    print("Programa detenido por teclado")
sys.exit(0)
