#!/usr/bin/env python3

'''
Script to run upload map
'''

import os
import sys

try:
    import pexpect
except ImportError:
    print('Required library "pexpect" not exists. Install with pip and try again')
    sys.exit(1)

# Define command
_COMMAND_ = 'python3 rooms_tool_client.py -p "%(map_server_proxy)s" %(token)s %(roomFile)s'

try:
    map_server_proxy, token, roomFile = sys.argv[1:]
except ValueError:
    print('Command arguments: {} <map_server_proxy> <token> <roomFile>'.format(
        os.path.basename(sys.argv[0]))
    )
    sys.exit(1)

# Compose command
final_command = _COMMAND_ % {
    'map_server_proxy': map_server_proxy,
    'token': token,
    'roomFile':roomFile
}

# Run command
proc = pexpect.spawn(final_command, echo=False)
try:
    proc.expect([pexpect.EOF])
except KeyboardInterrupt:
    print("Programa detenido por teclado")

#Show command output and exit
print(proc.before.decode().strip())
sys.exit(0)
